export const Houses = [
    {
        id: 1,
        owner_name: "Aarav Patel",
        gender: "Male",
        age: 40,
        owner_type: "owner",
        home_img: "house1.jpg",
        bhk_no: 3,
        address: "123 Main St, Mumbai, Maharashtra",
        rent: Math.min(10000, Math.floor(Math.random() * 10001)),
        home_size: 2000
    },
    {
        id: 2,
        owner_name: "Sneha Singh",
        gender: "female",
        age: 35,
        owner_type: "owner",
        home_img: "house2.jpg",
        bhk_no: 4,
        address: "456 Oak St, Delhi, Delhi",
        rent: Math.min(10000, Math.floor(Math.random() * 10001)),
        home_size: 2500
    },
    {
        id: 3,
        owner_name: "Vikram Sharma",
        gender: "Male",
        age: 55,
        owner_type: "owner",
        home_img: "house3.jpg",
        bhk_no: 2,
        address: "789 Pine St, Bangalore, Karnataka",
        rent: Math.min(10000, Math.floor(Math.random() * 10001)),
        home_size: 1500
    },
    {
        id: 4,
        owner_name: "Mitali Desai",
        gender: "female",
        age: 42,
        owner_type: "owner",
        home_img: "house4.jpg",
        bhk_no: 3,
        address: "321 Ashoka St, Kolkata, West Bengal",
        rent: Math.min(10000, Math.floor(Math.random() * 10001)),
        home_size: 1800
    },
    {
        id: 5,
        owner_name: "Rajesh Singh",
        gender: "Male",
        age: 50,
        owner_type: "owner",
        home_img: "house5.jpg",
        bhk_no: 2,
        address: "456 Palm St, Chennai, Tamil Nadu",
        rent: Math.min(10000, Math.floor(Math.random() * 10001)),
        home_size: 1200
    },
    {
        id: 6,
        owner_name: "Priya Chakraborty",
        gender: "female",
        age: 30,
        owner_type: "owner",
        home_img: "house6.jpg",
        bhk_no: 1,
        address: "789 Lotus St, Hyderabad, Telangana",
        rent: Math.min(10000, Math.floor(Math.random() * 10001)),
        home_size: 800
    },
    {
        id: 7,
        owner_name: "Amit Patel",
        gender: "Male",
        age: 45,
        owner_type: "owner",
        home_img: "house7.jpg",
        bhk_no: 3,
        address: "321 Tulip St, Pune, Maharashtra",
        rent: Math.min(10000, Math.floor(Math.random() * 10001)),
        home_size: 1600
    },
    {
        id: 8,
        owner_name: "Sangeeta Rao",
        gender: "female",
        age: 38,
        owner_type: "owner",
        home_img: "house8.jpg",
        bhk_no: 4,
        address: "456 Maple St, Jaipur, Rajasthan",
        rent: Math.min(10000, Math.floor(Math.random() * 10001)),
        home_size: 900
    },
    {
        id: 9,
        owner_name: "Sangeeta Rao",
        gender: "female",
        age: 38,
        owner_type: "owner",
        home_img: "house8.jpg",
        bhk_no: 4,
        address: "456 Maple St, Jaipur, Rajasthan",
        rent: Math.min(10000, Math.floor(Math.random() * 10001)),
        home_size: 900
    },
    {
        id: 10,
        owner_name: "Sangeeta Rao",
        gender: "female",
        age: 38,
        owner_type: "owner",
        home_img: "house8.jpg",
        bhk_no: 4,
        address: "456 Maple St, Jaipur, Rajasthan",
        rent: Math.min(10000, Math.floor(Math.random() * 10001)),
        home_size: 900
    }
]
